plot(reference.data_table{:,'t'},reference.data_table{:,'error'},'DisplayName','ptwise')
hold on; plot([0;reference.data_table{:,'t'}],sqrt(amin*cumtrapz([0;reference.data_table{:,'t'}],[0;reference.data_table{:,'error_H'}].^2)),'DisplayName','L^2')
plot(data_table{:,'t'}, data_table{:,'pi_x'},'-x','DisplayName','x')
plot(data_table{:,'t'}, data_table{:,'pi_t'},'-o','DisplayName','t')
plot(data_table{:,'t'}, data_table{:,'pi_y'},'-+','DisplayName','y')

writecell([{'t','x','t','y'}; num2cell([data_table{:,'t'},data_table{:,'pi_x'},data_table{:,'pi_t'},data_table{:,'pi_y'}])],...
    ['indicator-data-grid-' num2str(params.grid_param) '.dat'],'Delimiter','space');
writecell([{'t','L2','H1','E'};num2cell([[0;reference.data_table{:,'t'}],...
    [0;reference.data_table{:,'error'}],...
    sqrt(amin*cumtrapz([0;reference.data_table{:,'t'}],[0;reference.data_table{:,'error_H'}].^2)),...
    sqrt([0;reference.data_table{:,'error'}].^2 + amin*cumtrapz([0;reference.data_table{:,'t'}],[0;reference.data_table{:,'error_H'}].^2))])],...
    ['error-data-grid-' num2str(params.grid_param) '.dat'],'Delimiter','space');
