C = fast_TD_set(3,2);
I = smolyak_grid_multiidx_set(C, @(x)knots_CC(x,-1,1),@lev2knots_doubling);
Ir = reduce_sparse_grid(I);

figure;scatter3(Ir.knots(1,:),Ir.knots(2,:),Ir.knots(3,:));
writematrix(Ir.knots.','sparsegridd3k2.dat')

C = [1,1,1;...
1	1	2;...
1	2	1;...
1	2	2;...
2	1	1;...
2	1	2;...
2	2	1;...
2,2,2];
I = smolyak_grid_multiidx_set(C, @(x)knots_CC(x,-1,1),@lev2knots_doubling);
Ir = reduce_sparse_grid(I);

figure;scatter3(Ir.knots(1,:),Ir.knots(2,:),Ir.knots(3,:));
writematrix(Ir.knots.','gridd3k2.dat')